### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by lmarchetti02** [lmarchetti02/analisi-dati-tesi#2]
- [ ] Aggiungere grafici per vedere probabilità di transizione
- [ ] Implementare risoluzione sistema lineare
- [ ] Applicare correzioni su spettro monocromatico
